server:
  port: 8090

mybatis:
  mapper-locations: classpath:mappings/*.xml
  type-aliases-package: com.neuedu.personalmanagementsystem.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
